### ISSUE TITLE
What's the meaning of the initial orientation of the joint?

### ISSUE THREAD

**Issue by shuhonlin2** [Atiehmerikh/FABRIK_python#4]
Thank you for your work! 

I'm confused with the "orientation.txt: This is the initial orientation of each joint in quaternion." 

In the original paper, it said, "A bone rotation can be described by factoring it into two rotations: one ‘simple rotation’, termed here rotational (2 DoFs), that moves the bone to its final direction vector, and another which we call orientational (1 DoF), which represents the twist around this final vector."

Which kind of rotation are we referring to in "orientation.txt"?

Thank you for your work again!

**Comment by Leshphon-web** [comment]
Hello, did you come up with the results of this question ? because I have the same issue.

**Comment by Atiehmerikh** [comment]
> 

Thanks for your question. 

orientation.txt: This is the initial orientation of each joint in quaternion
each 3D body in space can be determined by its position and orientation. 
it can be specified in this text file with the quaternion format.
